### PR TITLE
improving is.truthy and is.falsy combination

### PR DESCRIPTION
**Pull request by ironmaniiith**
Current implementation:
```javascript
is.truthy(value) => !!value;
is.falsy(value)  => !!!value;
```
Improvised
```javascript
is.falsy(value)  => !value;
is.truthy(value) => !!value;
```

### CODE REVIEW

**Comment by jdalton** [comment]
Nice. I'm in the `falsey` spelling camp.

**Comment by ironmaniiith** [comment]
Nice, hope you goto `truthey` camp as well :stuck_out_tongue_winking_eye:

**Comment by jdalton** [comment]
Aww naw! For me it's `truth + y` and `false + y`

**Comment by ironmaniiith** [comment]
I guess you mean `'truth' +'y'` and `'false' + 'y'` :laughing:

**Comment by jdalton** [comment]
I went with `truey` before but folks lost their minds.

**Comment by ironmaniiith** [comment]
Hahahhahah :joy:

**Pull request merged**
