### PR TITLE
Add support for objects and arrays to `is.equal()`

### PR DESCRIPTION
**Pull request by tbasse**
Add support for both arrays and objects to `is.equal()` by comparing the JSON.stringified result of both values.

### CODE REVIEW

**Comment by webinfluenza** [comment]
Unlikely arrays, objects do not guarantee an internal order. So the comparison for object via JSON.stringify should be considered carefully.

`{foo: 1, bar: 2}` is actually equal to `{bar: 2, foo: 1}` but your test with JSON.stringify would fail.

ECMAScript (3rd edtition):
> 4.3.3 An object is a member of the type Object. It is an unordered collection of properties each of which contains a primitive value, object, or function. [...]

Still a good line of thought :-)

**Comment by arasatasaygin** [comment]
Thanks @tbasse 
As @webinfluenza said, string comparison is not a healthy method for this check. About the other commit:
Does explicit conversion have any advantage over implicit?

**Comment by tbasse** [comment]
@arasatasaygin Yeah, it occurred to me the day after that object key order isn't guaranteed across platforms/engines.

**Comment by arasatasaygin** [comment]
:) ok @tbasse

**Pull request closed without merging**
