### PR TITLE
is.empty written from scratch in is.js

### PR DESCRIPTION
**Pull request by ihopepeace**
The is.empty was buggy. It was returning true for the objects containing non-enumerable own properties only. Please review my implementation. 
In javascript falsy values are 0, NaN, undefined, null, false, "". is.truthy was returning true for 0, NaN & "". I have updated it. Please review my update.
Also, i recommend you to update test.js accordingly... As( should return true if given value is existy and not false) is a wrong assertion.

### CODE REVIEW

**Comment by arasatasaygin** [comment]
Thank you @ihopepeace 
Merged them.

**Comment by ihopepeace** [comment]
It was my first pull request. Thanks for your merging.

**Comment by arasatasaygin** [comment]
(⌐■_■)  Cool!

**Comment by cloudkite** [comment]
This implementation treats null, undefined and false as not being empty. Ie the following tests will fail

```
it('should treat false as empty', function() {
  expect(is.empty(false)).to.be.true;
});

it('should treat null as empty', function() {
  expect(is.empty(null)).to.be.true;
});

it('should treat undefined as empty', function() {
  expect(is.empty(undefined)).to.be.true;
});
```

Is this the desired behaviour? It differs from the lodash implementation of isEmpty https://lodash.com/docs#isEmpty

**Pull request merged**
