### PR TITLE
Add is.plainObject.

### PR DESCRIPTION
**Pull request by jcoc611**
Added method to check for strict objects `is.strictObject` in order to differentiate them from arrays (as opposed to `is.object`, which returns true for both). Also, stopped using `String.prototype.includes` in `is.include` because it is always returning false on Chrome.

### CODE REVIEW

**Comment by arasatasaygin** [comment]
Hey @jcoc611 
Thanks for the PR. I want to merge this one.
- What do you think about `is.planObject` instead of `is.strictObject`? Lots of libraries implemented the method under this name.
- Can you remove minified library? Because all of your changes are in a single commit and this file -is.min.js- has some merge conflicts. (I want your contribution to be seen on the repo. If I fix this on merge, changes will be seen as mine)

**Comment by jcoc611** [comment]
Hey @arasatasaygin 
I changed the method to `is.plainObject` as requested. Also, I deleted the minified library, although I'm not sure if that solves any merge issues. If there's something else I should modify please let me know.

**Comment by arasatasaygin** [comment]
Hey @jcoc611 
I was going to merge this but realised is.json() check is covering this case already. What do you think?

**Comment by jcoc611** [comment]
@arasatasaygin Actually, not quite. The code for `is.json` is wrong because serialized arrays, such as `"[1,2,3]"` are also valid JSON, per the [RFC Specification](http://www.ietf.org/rfc/rfc4627.txt). This means that a correct implementation of `is.json` should return true for both objects and arrays.

**Comment by jdalton** [comment]
@jcoc611 Could you remove the `is.include` fix from the PR.

**Comment by jdalton** [comment]
Closing as stale.

**Pull request closed without merging**
