### PR TITLE
maintaining `half` an integer in `is.palindrome`

### PR DESCRIPTION
**Pull request by ironmaniiith**

### CODE REVIEW

**Comment by jdalton** [comment]
@ironmaniiith Can you add a unit test for this.

**Comment by ironmaniiith** [comment]
Added. (even length palindromes, which may give the value of `half` as non integer)

**Comment by jdalton** [comment]
Thanks, the test seems to be passing without the change.

**Comment by ironmaniiith** [comment]
Yes it is, but `i` in the looping indicates the index here, which is terminating when `i <= half`, but half being non integer does not seems to be okay. Hence I thought of this change.

**Comment by jdalton** [comment]
It'd be better to find a failing test case. Also the `<< 0` will introduce edge case issues in large numbers. For example the max size of an array is `Math.pow(2,32)-1` or `4294967295` and
`4294967295 << 0` is `-1`. It's better to be explicit and use `Math.floor`.

**Comment by ironmaniiith** [comment]
The enhancement label looks fine, also there would be no failing test case as far as I can see.

**Comment by jdalton** [comment]
Looks good.

**Pull request merged**
