### PR TITLE
updated is.object

### PR DESCRIPTION
**Pull request by zekiunal**
Check type of value.

### CODE REVIEW

**Comment by zekiunal** [comment]
check value,  is it  true, false?  Okey, but you cant check "is true instanceof Boolean" 

if you try  "true instanceof Boolean" its return false, Becouse its not boolean object.

but , new Boolean(true) instanceof Boolean return true, if so you can check this contingency too

**Comment by zekiunal** [comment]
check this; 
   

function ExampleFunction(value) {
        this.xyz = value;
    }

    var abc = new ExampleFunction('Zeki');
    type = typeof ExampleFunction;
    alert(type); //function
    alert(abc instanceof Object); //true

**Comment by arasatasaygin** [comment]
All reference types are objects too.(instance of Object) Like:
```javascript
new Date() instanceof Object; //true
```

**Comment by arasatasaygin** [comment]
Decided to return true for all functions in this check, like you said. Thanks.

**Pull request merged**
