### PR TITLE
Adding stronger url regex validation to address issue #106

### PR DESCRIPTION
**Pull request by fslone**
Added the url regex suggested by @dperini in issue #106 that allows for optional protocol validation, returns true for url's containing parameter strings, returns false for url's containing spaces, etc.

### CODE REVIEW

**Comment by marqu3z** [comment]
+1

**Comment by fslone** [comment]
this also fixes the issue mentioned in #121

**Comment by arasatasaygin** [comment]
Thanks for the PR @fslone

**Comment by fslone** [comment]
Glad to help. Let me know if there are any other things you'd like help adding or fixing, really like this project a lot.

**Comment by arasatasaygin** [comment]
Appreciate it @fslone

**Pull request merged**
