### PR TITLE
bug fix > is.decimal

### PR DESCRIPTION
**Pull request by ironmaniiith**
Bug Description:
```javascript
is.decimal(1.0);
// false
```

### CODE REVIEW

**Comment by jdalton** [comment]
I'm not seeing `1.0` convert to `"1.0"` when coerced to a string.

**Comment by ironmaniiith** [comment]
Oh sorry, will fix it
Thanks :+1:

**Comment by ironmaniiith** [comment]
Oh, well...
Can this be even done given that the input is provided as a number.?

**Comment by jdalton** [comment]
I don't believe so.

**Pull request closed without merging**
