### PR TITLE
Fix for #77 - adds is.whitespace check

### PR DESCRIPTION
**Pull request by jonhester**
https://github.com/arasatasaygin/is.js/issues/77

### CODE REVIEW

**Comment by mvgijssel** [comment]
Why is this closed as wontfix? This would actually be really useful!

**Comment by jdalton** [comment]
You'll need to vote on the feature over at #77. Dude just opened a PR assuming it would be instamerged which is not the case round here.

**Comment by jonhester** [comment]
@jdalton Not sure what you mean by assuming it would be instamerged. I opened a pull request based on #77, and then updated it based on discussion. Finally, I was fine with it not being merged. I've also had other pull requests to this project merged.

**Comment by mvgijssel** [comment]
Ah sorry, reading is hard 🙈 . Will up vote!

**Comment by jonhester** [comment]
@jdalton, you changed your comment but didn't respond to mine. The contribution guidelines were different when I submitted this pull request https://github.com/arasatasaygin/is.js/commit/e7c2e919ad0d90fbed7cd3f637d46f8ffb1fdaff.

**Pull request closed without merging**
