### PR TITLE
Added .gitattributes file & "is.ip() is.ipv4 & is.ipv6()" methods

### PR DESCRIPTION
**Pull request by ihopepeace**
Its a good practice to include .gitattributes file. You can know the reason here https://help.github.com/articles/dealing-with-line-endings/
Since the repository is becoming popular nd popular I highly recommend you to merge this.
Also refreash the repository after merging .gitattributes. This link will help you https://help.github.com/articles/dealing-with-line-endings/#refreshing-a-repository-after-changing-line-endings

### CODE REVIEW

**Comment by arasatasaygin** [comment]
This is an interesting issue. Thanks @ihopepeace 
I'll read about it and merge.
Cheers.

**Comment by ihopepeace** [comment]
@arasatasaygin I noticed that in most of the people don't bother to include .gitattributes. May be because it requires to read a bit. So, I have created a .gitattributes file generator. You are welcomed to try it & contribute to it...
http://ihopepeace.github.io/gitattributes_generator/

**Comment by arasatasaygin** [comment]
Cool, I'll definitely look at it.

**Comment by ihopepeace** [comment]
Thanks :)

**Comment by ihopepeace** [comment]
@arasatasaygin I m new to this community... So, I will need a lot of help from you...  I think this generator is cool for 2 reasons:
a) .gitattributes is the most effective way till now to remove the issues of line ending, still most of the people ignore it. Probably because they have to go through documentation.
b) It will allow them to generate .gitattribute file exclusively for their project without any need of reading documentation...

**Comment by ihopepeace** [comment]
Can you merge this pull request soon... I want to create a new pull request.

**Comment by AlexandreAWE** [comment]
+1 for the PR

**Comment by ihopepeace** [comment]
@arasatasaygin Am I doing something wrong? I have a queue of PR waiting.... Please merge them or let me know what am I doing wrong.. I am new to this community.. So, please help me
Thanks

**Comment by arasatasaygin** [comment]
Nope, sorry for the late response.
Thanks for all the PRs. They look pretty cool @ihopepeace 
I'll look them today and merge. Cheers.

**Comment by ihopepeace** [comment]
Thanks @arasatasaygin

**Comment by arasatasaygin** [comment]
Thanks for all the PRs @ihopepeace 
Merged them.

**Pull request closed without merging**
