### PR TITLE
`value:string` > `value:any` for ip, ipv4, ipv6 in README

### PR DESCRIPTION
**Pull request by ironmaniiith**
Refer #228

### CODE REVIEW

**Comment by jdalton** [comment]
Could you see any other non-string value being used? I take the param type as a preferred type.

**Comment by ironmaniiith** [comment]
So for example if  I do.
`is.ip(1234.1234)`
Then it returns false, so basically we are entertaining the user even if the param given is of another type (which is currently the case with most of the other RegExp checks as well).

However, I see no point of doing this (and even in other).
So should this be changed for the other methods as well.?

**Comment by jdalton** [comment]
Ya I think it should be changed (we can always unofficially support it but I don't think the docs should encourage non-strings here).

**Comment by ironmaniiith** [comment]
But things like.
```javascript
is.not.url(true);
is.not.ip(127001);
is.any.socialSecurityNumber(12312, '017-90-7890');
```
which are valid, encourages the use of other type of params as well.?

**Comment by jdalton** [comment]
Ah I see. Since the `is` api is all about questions I can see any being used for much of it.

**Comment by ironmaniiith** [comment]
So I guess this PR works fine.?

**Comment by jdalton** [comment]
😋

**Pull request merged**
