### PR TITLE
preventing running off the array index in `is.sorted`

### PR DESCRIPTION
**Pull request by ironmaniiith**

### CODE REVIEW

**Comment by jdalton** [comment]
Can you add a unit test?

**Comment by ironmaniiith** [comment]
The current implementation is such that the condition under if always evaluates to false (comparison b/w number and undefined). Hence no buggy behaviour I guess.

**Comment by jdalton** [comment]
Could you ensure there's a test for this anyways.

**Comment by ironmaniiith** [comment]
Previous implementation may create confusion, cause in that case when array is single sized, comparison is only between the `number` and `undefined`, hence I added one more test for it. Rest all is fine.

**Comment by ironmaniiith** [comment]
Closing this, moved to #220

**Pull request merged**
