### PR TITLE
Add is MAC address regex

### PR DESCRIPTION
**Pull request by weiland**

### CODE REVIEW

**Comment by ironmaniiith** [comment]
@weiland, could you make a fresh PR for this?

**Comment by weiland** [comment]
@ironmaniiith sure!

**Comment by evdama** [comment]
@weiland I've added the `macAddress` check https://github.com/evdama/is-it-check#ismacaddressvalueany

**Comment by weiland** [comment]
Perfect, thank you! I will close this PR.

**Comment by evdama** [comment]
All tests of course pass without errors but have a look at the code and maybe review again 🤓
https://github.com/evdama/is-it-check/commit/003cf6339fb157b1eb8f0b8de833818800da18e6

**Pull request closed without merging**
